### PR TITLE
Upgrade rubocop to 0.34.0 from 0.33.0

### PR DESCRIPTION
**Pull request by backus**

### CODE REVIEW

**Comment by mbj** [comment]
Does this fix https://github.com/mbj/devtools/issues/81? So will the cache feature be used automagically, or do we have to configure it?

**Comment by backus** [comment]
Cache is enabled by default

**Comment by mbj** [comment]
@backus thx.

**Comment by dkubb** [comment]
Since the PR fixed #81, we would generally add `[Fix #81]` to the description so that when this is merged github automatically closes the related issue. This can also work in individual commits.

**Comment by backus** [comment]
Ah well I included `closes #81` in the commit body.  That didn't close it?

**Comment by backus** [comment]
I just remove it from the description when github fills that in because I don't like the duplicate references it clutters the issue with

**Comment by dkubb** [comment]
@backus Oh sorry, I missed that.

**Comment by backus** [comment]
No problem. I can leave it in the issue description too if that is preferred

**Comment by dkubb** [comment]
> No problem. I can leave it in the issue description too if that is preferred

I don't have a strong preference on it. Typically what I do is put it in the PR description if a *set* of commits fixes an issue, and put it in the individual commit if I could cherry-pick *just* that commit into master to fix the issue. I sometimes screw up and forget though. The most important thing is that it be referenced somewhere.

**Pull request merged**
