### PR TITLE
Use mutant 0.8.1 and support --since

### PR DESCRIPTION
**Pull request by backus**

### CODE REVIEW

**Comment by dkubb** [comment]
@backus What do you think about adding `since: HEAD~1` to `config/mutant.yml`?

This would require that every future commit to [mbj/devtools](https://github.com/mbj/devtools) will require mutation coverage of modified code, which imho is a good idea.

**Comment by backus** [comment]
Would you want to enable mutation testing for devtools itself too then? Mutant is disabled for devtools itself I believe: [line 18 of mutant.rake](https://github.com/mbj/devtools/blob/master/tasks/metrics/mutant.rake#L18)

**Comment by dkubb** [comment]
@backus I *think* that's because at the time devtools was written before mutant and there was a ton of specs we'd need to backfill and we didn't think it was worth the effort at the time. However, in this case, we can "draw a line in the sand" and say that all future changes must be mutation covered, which I think is a good compromise.

@mbj wdyt?

**Comment by mbj** [comment]
> However, in this case, we can "draw a line in the sand" and say that all future changes must be mutation covered, which I think is a good compromise.

Lets do that, but not in this PR. This one is about adding a configuration option, not improving devtools build setup.

Also note I want to totally rewrite devtools, for supporting local and container paralellism, based on mutants actor implementation. This way we can speed up builds on containerized platforms such as circle CI.

Also mutant has a long standing branch for adding its own (much more powerful) config file support, that ultimatively will make a larger portion of devtools features redundant. https://github.com/mbj/mutant/pull/247

**Comment by mbj** [comment]
@backus Thx for your contribution.

**Comment by dkubb** [comment]
> Lets do that, but not in this PR

@mbj Ok sounds good to me. We can make a follow-up PR that adds this.

**Pull request merged**
