### PR TITLE
Update to rubocop 0.52.1, rake 12.3, simplecov 0.15.1 and yard 0.9.12

### PR DESCRIPTION
**Pull request by zaidan**

### CODE REVIEW

**Comment by mbj** [comment]
Yes, I'm fine constraining ruby to a newer release. People who want older rubies have simply to use older software.

@zaidan While you are on it, do you want to consider bumping the yard dep? (via yardstick if needed)?

**Comment by zaidan** [comment]
@mbj ok will bump yard, too. yardstick is up to date. I could upgrade rspec to 3.7, but mutant-rspec requires < 3.7

**Comment by mbj** [comment]
@zaidan `mutant-rspec` has an open PR to bump to newer rspec, but its blocked by a (likely easy to address) corpus failure.

Also I'd at this point accept changing the `mutant-rspec` dependency on `rspec` to `~>3.7`. The private interface I hook into is pretty stable.

**Comment by mbj** [comment]
> @mbj oh you have already merged it. I will change the title and open a new pull request for the dependencies.

I do not mind merging things that improve the system, even if the improvement only leads us to a weaker than possible local maximum.

To me its important that we do not add regressions.

**Pull request merged**
