### PR TITLE
Bump reek dependency to ~> 3.0.4

### PR DESCRIPTION
**Pull request by backus**
Requested in #73

### CODE REVIEW

**Comment by mbj** [comment]
Thx, I wounder why jruby fails.

**Comment by backus** [comment]
It looks like jruby failed for #71 ([travis build](https://travis-ci.org/mbj/devtools/builds/66761090))

**Comment by backus** [comment]
Seems related to this @mbj https://github.com/jruby/jruby/issues/1595

**Comment by mbj** [comment]
@backus Lets just move jruby to allowed failures meanwhile.

**Comment by backus** [comment]
k.  Travis matrix updated

**Comment by backus** [comment]
I don't know why rubinius now decided to fail now... Rerunning multiple times on my branch seemed to result in a few passes and one fail.

**Comment by mbj** [comment]
Lets also move rbx to allowed failures than.

**Comment by backus** [comment]
:+1: updated

**Comment by mbj** [comment]
@backus Thx. Merged.

**Pull request merged**
