### PR TITLE
Update rake to 12.0.0

### PR DESCRIPTION
**Pull request by zaidan**

### CODE REVIEW

**Comment by mbj** [comment]
@zaidan For some reason the CircleCI build does not trigger, can you re-push these commits as it may be a temporal problem with GH webhooks / CircleCI?

**Comment by zaidan** [comment]
@mbj Ok i tried a git reset HEAD~, re-commited and force pushed the last commit.

**Comment by mbj** [comment]
@zaidan Can you also force push the first commit, than normal push the last commit? I'd really like to have each commit in a PR passing.

I'd also be fine if you squash them.

**Comment by backus** [comment]
@zaidan if you add me as a collaborator on your fork I can help you force push each commit. We use a special command to do this normally. [`git push-each`](https://github.com/dkubb/git-tools/blob/master/git-push-each)

**Comment by zaidan** [comment]
@backus thanks for the command. I tried a reset to commit 1e9ff3c, then force pushed, then pushed all commit separately. Each one triggered a CircleCI Build, all passed:
https://github.com/zaidan/devtools/commits/master

All three commits have green check marks in my history, but in the PR only the last one has a green check mark.

I will try the git push each command and if this does not work i will add you as collaborator :-)

**Pull request merged**
